export const ACTIONS = {
  TOGGLE: "TOGGLE",
  CART: "CART",
  UPDATECART: "UPDATECART",
  DELETECART: "DELETECART",
  SETCART: "SETCART",
  LOADING: "LOADING",
  FAVOURITE: "FAVOURITE",
  UPDATEFAVOURITE: "UPDATEFAVOURITE",
  DELETEFAVOURITE: "DELETEFAVOURITE",
  SETFAVOURITE: "SETFAVOURITE",
  CALLBACK: "CALLBACK",
};
