import { v4 as uuidv4 } from "uuid";

export const data = [
  {
    id: uuidv4(),
    title: "Flower vase",
    price: "100",
    category: "flower",
    ratings: "",
    images: [
      "/images/product1.svg",
      "/images/product1.svg",
      "/images/product1.svg",
      "/images/product1.svg",
      "/images/product1.svg",
      "/images/product1.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Exotic Curtains",
    price: "100",
    category: "curtains",
    ratings: "",
    images: [
      "/images/product6.svg",
      "/images/product6.svg",
      "/images/product6.svg",
      "/images/product6.svg",
      "/images/product6.svg",
      "/images/product6.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Hanging Lights",
    price: "100",
    category: "lights",
    ratings: "",
    images: [
      "/images/product7.svg",
      "/images/product7.svg",
      "/images/product7.svg",
      "/images/product7.svg",
      "/images/product7.svg",
      "/images/product7.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Round Lift Nesting Table",
    price: "100",
    category: "table",
    ratings: "",
    images: [
      "/images/product8.svg",
      "/images/product8.svg",
      "/images/product8.svg",
      "/images/product8.svg",
      "/images/product8.svg",
      "/images/product8.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Elephant Tusk Ceramics",
    price: "100",
    category: "ceramics",
    ratings: "",
    images: [
      "/images/product9.svg",
      "/images/product9.svg",
      "/images/product9.svg",
      "/images/product9.svg",
      "/images/product9.svg",
      "/images/product9.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Luxury Marble End Table",
    price: "100",
    category: "table",
    ratings: "",
    images: [
      "/images/product10.svg",
      "/images/product10.svg",
      "/images/product10.svg",
      "/images/product10.svg",
      "/images/product10.svg",
      "/images/product10.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Abstract Ceramic Scupture",
    price: "100",
    category: "ceramics",
    ratings: "",
    images: [
      "/images/product3.svg",
      "/images/product3.svg",
      "/images/product3.svg",
      "/images/product3.svg",
      "/images/product3.svg",
      "/images/product3.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Hanging Lights",
    price: "100",
    category: "light",
    ratings: "",
    images: [
      "/images/product2.svg",
      "/images/product2.svg",
      "/images/product2.svg",
      "/images/product2.svg",
      "/images/product2.svg",
      "/images/product2.svg",
    ],
  },
  {
    id: uuidv4(),
    title: "Decorative Soda Chair",
    price: "100",
    category: "chair",
    ratings: "",
    images: [
      "/images/product5.svg",
      "/images/product5.svg",
      "/images/product5.svg",
      "/images/product5.svg",
      "/images/product5.svg",
      "/images/product5.svg",
    ],
  },
];
