const statesData = [
  {
    value: "Abia",
    label: "Abia",
    lgas: [
      {
        label: "Aba North",
        value: "Aba North",
      },
      {
        label: "Aba South",
        value: "Aba South",
      },
      {
        label: "Arochukwu",
        value: "Arochukwu",
      },
      {
        label: "Bende",
        value: "Bende",
      },
      {
        label: "Ikawuno",
        value: "Ikawuno",
      },
      {
        label: "Ikwuano",
        value: "Ikwuano",
      },
      {
        label: "Isiala-Ngwa North",
        value: "Isiala-Ngwa North",
      },
      {
        label: "Isiala-Ngwa South",
        value: "Isiala-Ngwa South",
      },
      {
        label: "Isuikwuato",
        value: "Isuikwuato",
      },

      { label: "Obi Ngwa", value: "Obi Ngwa" },
      { label: "Obioma Ngwa", value: "Obioma Ngwa" },
      { label: "Ohafia", value: "Ohafia" },
      { label: "Ohaozara", value: "Ohaozara" },
      { label: "Osisioma", value: "Osisioma" },
      { label: "Ugwunagbo", value: "Ugwunagbo" },
      { label: "Ukwa West", value: "Ukwa West" },
      { label: "Ukwa East", value: "Ukwa East" },
      { label: "Umuahia North", value: "Umuahia North" },
      { label: "Umuahia South", value: "Umuahia South" },
    ],
  },
  {
    value: "Adamawa",
    label: "Adamawa",
    lgas: [
      { label: "Demsa", value: "Demsa" },
      { label: "Fufore", value: "Fufore" },
      { label: "Ganye", value: "Ganye" },
      { label: "Girei", value: "Girei" },
      { label: "Gombi", value: "Gombi" },
      { label: "Guyuk", value: "Guyuk" },
      { label: "Hong", value: "Hong" },
      { label: "Jada", value: "Jada" },
      { label: "Lamurde", value: "Lamurde" },
      { label: "Madagali", value: "Madagali" },
      { label: "Maiha", value: "Maiha" },
      { label: "Mayo-Belwa", value: "Mayo-Belwa" },
      { label: "Michika", value: "Michika" },
      { label: "Mubi-North", value: "Mubi-North" },
      { label: "Mubi-South", value: "Mubi-South" },
      { label: "Numan", value: "Numan" },
      { label: "Shelleng", value: "Shelleng" },
      { label: "Song", value: "Song" },
      { label: "Toungo", value: "Toungo" },
      { label: "Yola North", value: "Yola North" },
      { label: "Yola South", value: "Yola South" },
    ],
  },
  {
    value: "Akwa Ibom",
    label: "Akwa Ibom",
    lgas: [
      { label: "Abak", value: "Abak" },
      { label: "Eastern-Obolo", value: "Eastern-Obolo" },
      { label: "Eket", value: "Eket" },
      { label: "Esit-Eket", value: "Esit-Eket" },
      { label: "Essien-Udim", value: "Essien-Udim" },
      { label: "Etim-Ekpo", value: "Etim-Ekpo" },
      { label: "Etinan", value: "Etinan" },
      { label: "Ibeno", value: "Ibeno" },
      { label: "Ibesikpo-Asutan", value: "Ibesikpo-Asutan" },
      { label: "Ibiono-Ibom", value: "Ibiono-Ibom" },
      { label: "Ika", value: "Ika" },
      { label: "Ikono", value: "Ikono" },
      { label: "Ikot-Abasi", value: "Ikot-Abasi" },
      { label: "Ikot-Ekpene", value: "Ikot-Ekpene" },
      { label: "Ini", value: "Ini" },
      { label: "Itu", value: "Itu" },
      { label: "Mbo", value: "Mbo" },
      { label: "Mkpat-Enin", value: "Mkpat-Enin" },
      { label: "Nsit-Atai", value: "Nsit-Atai" },
      { label: "Nsit-Ibom", value: "Nsit-Ibom" },
      { label: "Nsit-Ubium", value: "Nsit-Ubium" },
      { label: "Obot-Akara", value: "Obot-Akara" },
      { label: "Okobo", value: "Okobo" },
      { label: "Onna", value: "Onna" },
      { label: "Oron", value: "Oron" },
      { label: "Oruk Anam", value: "Oruk Anam" },
      { label: "Udung-Uko", value: "Udung-Uko" },
      { label: "Ukanafun", value: "Ukanafun" },
      { label: "Urue-Offong/Oruko", value: "Urue-Offong/Oruko" },
      { label: "Uruan", value: "Uruan" },
      { label: "Uyo", value: "Uyo" },
    ],
  },
  {
    value: "Anambra",
    label: "Anambra",
    lgas: [
      { label: "Aguata", value: "Aguata" },
      { label: "Anambra East", value: "Anambra East" },
      { label: "Anambra West", value: "Anambra West" },
      { label: "Anaocha", value: "Anaocha" },
      { label: "Awka North", value: "Awka North" },
      { label: "Awka South", value: "Awka South" },
      { label: "Ayamelum", value: "Ayamelum" },
      { label: "Dunukofia", value: "Dunukofia" },
      { label: "Ekwusigo", value: "Ekwusigo" },
      { label: "Idemili-North", value: "Idemili-North" },
      { label: "Idemili-South", value: "Idemili-South" },
      { label: "Ihiala", value: "Ihiala" },
      { label: "Njikoka", value: "Njikoka" },
      { label: "Nnewi-North", value: "Nnewi-North" },
      { label: "Nnewi-South", value: "Nnewi-South" },
      { label: "Ogbaru", value: "Ogbaru" },
      { label: "Onitsha-North", value: "Onitsha-North" },
      { label: "Onitsha-South", value: "Onitsha-South" },
      { label: "Orumba-North", value: "Orumba-North" },
      { label: "Orumba-South", value: "Orumba-South" },
    ],
  },
  {
    value: "Bauchi",
    label: "Bauchi",
    lgas: [
      { label: "Alkaleri", value: "Alkaleri" },
      { label: "Bauchi", value: "Bauchi" },
      { label: "Bogoro", value: "Bogoro" },
      { label: "Damban", value: "Damban" },
      { label: "Darazo", value: "Darazo" },
      { label: "Dass", value: "Dass" },
      { label: "Gamawa", value: "Gamawa" },
      { label: "Ganjuwa", value: "Ganjuwa" },
      { label: "Giade", value: "Giade" },
      { label: "Itas/Gadau", value: "Itas/Gadau" },
      { label: "Jama'Are", value: "Jama'Are" },
      { label: "Katagum", value: "Katagum" },
      { label: "Kirfi", value: "Kirfi" },
      { label: "Misau", value: "Misau" },
      { label: "Ningi", value: "Ningi" },
      { label: "Shira", value: "Shira" },
      { label: "Tafawa-Balewa", value: "Tafawa-Balewa" },
      { label: "Toro", value: "Toro" },
      { label: "Warji", value: "Warji" },
      { label: "Zaki", value: "Zaki" },
    ],
  },
  {
    value: "Benue",
    label: "Benue",
    lgas: [
      { label: "Ado", value: "Ado" },
      { label: "Agatu", value: "Agatu" },
      { label: "Apa", value: "Apa" },
      { label: "Buruku", value: "Buruku" },
      { label: "Gboko", value: "Gboko" },
      { label: "Guma", value: "Guma" },
      { label: "Gwer-East", value: "Gwer-East" },
      { label: "Gwer-West", value: "Gwer-West" },
      { label: "Katsina-Ala", value: "Katsina-Ala" },
      { label: "Konshisha", value: "Konshisha" },
      { label: "Kwande", value: "Kwande" },
      { label: "Logo", value: "Logo" },
      { label: "Makurdi", value: "Makurdi" },
      { label: "Ogbadibo", value: "Ogbadibo" },
      { label: "Ohimini", value: "Ohimini" },
      { label: "Oju", value: "Oju" },
      { label: "Okpokwu", value: "Okpokwu" },
      { label: "Otukpo", value: "Otukpo" },
      { label: "Tarka", value: "Tarka" },
      { label: "Ukum", value: "Ukum" },
      { label: "Ushongo", value: "Ushongo" },
      { label: "Vandeikya", value: "Vandeikya" },
    ],
  },
  {
    value: "Borno",
    label: "Borno",
    lgas: [
      { label: "Abadam", value: "Abadam" },
      { label: "Askira-Uba", value: "Askira-Uba" },
      { label: "Bama", value: "Bama" },
      { label: "Bayo", value: "Bayo" },
      { label: "Biu", value: "Biu" },
      { label: "Chibok", value: "Chibok" },
      { label: "Damboa", value: "Damboa" },
      { label: "Dikwa", value: "Dikwa" },
      { label: "Gubio", value: "Gubio" },
      { label: "Guzamala", value: "Guzamala" },
      { label: "Gwoza", value: "Gwoza" },
      { label: "Hawul", value: "Hawul" },
      { label: "Jere", value: "Jere" },
      { label: "Kaga", value: "Kaga" },
      { label: "Kala/Balge", value: "Kala/Balge" },
      { label: "Konduga", value: "Konduga" },
      { label: "Kukawa", value: "Kukawa" },
      { label: "Kwaya-Kusar", value: "Kwaya-Kusar" },
      { label: "Mafa", value: "Mafa" },
      { label: "Magumeri", value: "Magumeri" },
      { label: "Maiduguri", value: "Maiduguri" },
      { label: "Marte", value: "Marte" },
      { label: "Mobbar", value: "Mobbar" },
      { label: "Monguno", value: "Monguno" },
      { label: "Ngala", value: "Ngala" },
      { label: "Nganzai", value: "Nganzai" },
      { label: "Shani", value: "Shani" },
    ],
  },
  {
    value: "Bayelsa",
    label: "Bayelsa",
    lgas: [
      { label: "Brass", value: "Brass" },
      { label: "Ekeremor", value: "Ekeremor" },
      { label: "Kolokuma/Opokuma", value: "Kolokuma/Opokuma" },
      { label: "Nembe", value: "Nembe" },
      { label: "Ogbia", value: "Ogbia" },
      { label: "Sagbama", value: "Sagbama" },
      { label: "Southern-Ijaw", value: "Southern-Ijaw" },
      { label: "Yenagoa", value: "Yenagoa" },
    ],
  },
  {
    value: "Cross River",
    label: "Cross River",
    lgas: [
      { label: "Abi", value: "Abi" },
      { label: "Akamkpa", value: "Akamkpa" },
      { label: "Akpabuyo", value: "Akpabuyo" },
      { label: "Bakassi", value: "Bakassi" },
      { label: "Bekwarra", value: "Bekwarra" },
      { label: "Biase", value: "Biase" },
      { label: "Boki", value: "Boki" },
      { label: "Calabar-Municipal", value: "Calabar-Municipal" },
      { label: "Calabar-South", value: "Calabar-South" },
      { label: "Etung", value: "Etung" },
      { label: "Ikom", value: "Ikom" },
      { label: "Obanliku", value: "Obanliku" },
      { label: "Obubra", value: "Obubra" },
      { label: "Obudu", value: "Obudu" },
      { label: "Odukpani", value: "Odukpani" },
      { label: "Ogoja", value: "Ogoja" },
      { label: "Yakurr", value: "Yakurr" },
      { label: "Yala", value: "Yala" },
    ],
  },
  {
    value: "Delta",
    label: "Delta",
    lgas: [
      { label: "Aniocha North", value: "Aniocha North" },
      { label: "Aniocha-North", value: "Aniocha-North" },
      { label: "Aniocha-South", value: "Aniocha-South" },
      { label: "Bomadi", value: "Bomadi" },
      { label: "Burutu", value: "Burutu" },
      { label: "Ethiope-East", value: "Ethiope-East" },
      { label: "Ethiope-West", value: "Ethiope-West" },
      { label: "Ika-North-East", value: "Ika-North-East" },
      { label: "Ika-South", value: "Ika-South" },
      { label: "Isoko-North", value: "Isoko-North" },
      { label: "Isoko-South", value: "Isoko-South" },
      { label: "Ndokwa-East", value: "Ndokwa-East" },
      { label: "Ndokwa-West", value: "Ndokwa-West" },
      { label: "Okpe", value: "Okpe" },
      { label: "Oshimili-North", value: "Oshimili-North" },
      { label: "Oshimili-South", value: "Oshimili-South" },
      { label: "Patani", value: "Patani" },
      { label: "Sapele", value: "Sapele" },
      { label: "Udu", value: "Udu" },
      { label: "Ughelli-North", value: "Ughelli-North" },
      { label: "Ughelli-South", value: "Ughelli-South" },
      { label: "Ukwuani", value: "Ukwuani" },
      { label: "Uvwie", value: "Uvwie" },
      { label: "Warri South-West", value: "Warri South-West" },
      { label: "Warri North", value: "Warri North" },
      { label: "Warri South", value: "Warri South" },
    ],
  },
  {
    value: "Ebonyi",
    label: "Ebonyi",
    lgas: [
      { label: "Abakaliki", value: "Abakaliki" },
      { label: "Afikpo-North", value: "Afikpo-North" },
      { label: "Afikpo South (Edda)", value: "Afikpo South (Edda)" },
      { label: "Ebonyi", value: "Ebonyi" },
      { label: "Ezza-North", value: "Ezza-North" },
      { label: "Ezza-South", value: "Ezza-South" },
      { label: "Ikwo", value: "Ikwo" },
      { label: "Ishielu", value: "Ishielu" },
      { label: "Ivo", value: "Ivo" },
      { label: "Izzi", value: "Izzi" },
      { label: "Ohaukwu", value: "Ohaukwu" },
      { label: "Onicha", value: "Onicha" },
    ],
  },
  {
    value: "Edo",
    label: "Edo",
    lgas: [
      { label: "Akoko Edo", value: "Akoko Edo" },
      { label: "Egor", value: "Egor" },
      { label: "Esan-Central", value: "Esan-Central" },
      { label: "Esan-North-East", value: "Esan-North-East" },
      { label: "Esan-South-East", value: "Esan-South-East" },
      { label: "Esan-West", value: "Esan-West" },
      { label: "Etsako-Central", value: "Etsako-Central" },
      { label: "Etsako-East", value: "Etsako-East" },
      { label: "Etsako-West", value: "Etsako-West" },
      { label: "Igueben", value: "Igueben" },
      { label: "Ikpoba-Okha", value: "Ikpoba-Okha" },
      { label: "Oredo", value: "Oredo" },
      { label: "Orhionmwon", value: "Orhionmwon" },
      { label: "Ovia-North-East", value: "Ovia-North-East" },
      { label: "Ovia-South-West", value: "Ovia-South-West" },
      { label: "Owan East", value: "Owan East" },
      { label: "Owan-West", value: "Owan-West" },
      { label: "Uhunmwonde", value: "Uhunmwonde" },
    ],
  },
  {
    value: "Ekiti",
    label: "Ekiti",
    lgas: [
      { label: "Ado-Ekiti", value: "Ado-Ekiti" },
      { label: "Efon", value: "Efon" },
      { label: "Ekiti-East", value: "Ekiti-East" },
      { label: "Ekiti-South-West", value: "Ekiti-South-West" },
      { label: "Ekiti-West", value: "Ekiti-West" },
      { label: "Emure", value: "Emure" },
      { label: "Gbonyin", value: "Gbonyin" },
      { label: "Ido-Osi", value: "Ido-Osi" },
      { label: "Ijero", value: "Ijero" },
      { label: "Ikere", value: "Ikere" },
      { label: "Ikole", value: "Ikole" },
      { label: "Ilejemeje", value: "Ilejemeje" },
      { label: "Irepodun/Ifelodun", value: "Irepodun/Ifelodun" },
      { label: "Ise-Orun", value: "Ise-Orun" },
      { label: "Moba", value: "Moba" },
      { label: "Oye", value: "Oye" },
    ],
  },
  {
    value: "Enugu",
    label: "Enugu",
    lgas: [
      { label: "Aninri", value: "Aninri" },
      { label: "Awgu", value: "Awgu" },
      { label: "Enugu-East", value: "Enugu-East" },
      { label: "Enugu-North", value: "Enugu-North" },
      { label: "Enugu-South", value: "Enugu-South" },
      { label: "Ezeagu", value: "Ezeagu" },
      { label: "Igbo-Etiti", value: "Igbo-Etiti" },
      { label: "Igbo-Eze-North", value: "Igbo-Eze-North" },
      { label: "Igbo-Eze-South", value: "Igbo-Eze-South" },
      { label: "Isi-Uzo", value: "Isi-Uzo" },
      { label: "Nkanu-East", value: "Nkanu-East" },
      { label: "Nkanu-West", value: "Nkanu-West" },
      { label: "Nsukka", value: "Nsukka" },
      { label: "Oji-River", value: "Oji-River" },
      { label: "Udenu", value: "Udenu" },
      { label: "Udi", value: "Udi" },
      { label: "Uzo-Uwani", value: "Uzo-Uwani" },
    ],
  },
  // {
  //   value: "Federal Capital Territory",
  //   label: "Federal Capital Territory",
  //   lgas: [
  //     { label: "Abuja", value: "Abuja" },
  //     { label: "Kwali", value: "Kwali" },
  //     { label: "Kuje", value: "Kuje" },
  //     { label: "Gwagwalada", value: "Gwagwalada" },
  //     { label: "Bwari", value: "Bwari" },
  //     { label: "Abaji", value: "Abaji" },
  //   ],
  // },
  {
    value: "Gombe",
    label: "Gombe",
    lgas: [
      { label: "Akko", value: "Akko" },
      { label: "Balanga", value: "Balanga" },
      { label: "Billiri", value: "Billiri" },
      { label: "Dukku", value: "Dukku" },
      { label: "Funakaye", value: "Funakaye" },
      { label: "Gombe", value: "Gombe" },
      { label: "Kaltungo", value: "Kaltungo" },
      { label: "Kwami", value: "Kwami" },
      { label: "Nafada", value: "Nafada" },
      { label: "Shongom", value: "Shongom" },
      { label: "Yamaltu/Deba", value: "Yamaltu/Deba" },
    ],
  },
  {
    value: "Imo",
    label: "Imo",
    lgas: [
      { label: "Aboh-Mbaise", value: "Aboh-Mbaise" },
      { label: "Ahiazu-Mbaise", value: "Ahiazu-Mbaise" },
      { label: "Ehime-Mbano", value: "Ehime-Mbano" },
      { label: "Ezinihitte", value: "Ezinihitte" },
      { label: "Ideato-North", value: "Ideato-North" },
      { label: "Ideato-South", value: "Ideato-South" },
      { label: "Ihitte/Uboma", value: "Ihitte/Uboma" },
      { label: "Ikeduru", value: "Ikeduru" },
      { label: "Isiala-Mbano", value: "Isiala-Mbano" },
      { label: "Isu", value: "Isu" },
      { label: "Mbaitoli", value: "Mbaitoli" },
      { label: "Ngor-Okpala", value: "Ngor-Okpala" },
      { label: "Njaba", value: "Njaba" },
      { label: "Nkwerre", value: "Nkwerre" },
      { label: "Nwangele", value: "Nwangele" },
      { label: "Obowo", value: "Obowo" },
      { label: "Oguta", value: "Oguta" },
      { label: "Ohaji-Egbema", value: "Ohaji-Egbema" },
      { label: "Okigwe", value: "Okigwe" },
      { label: "Onuimo", value: "Onuimo" },
      { label: "Orlu", value: "Orlu" },
      { label: "Orsu", value: "Orsu" },
      { label: "Oru-East", value: "Oru-East" },
      { label: "Oru-West", value: "Oru-West" },
      { label: "Owerri-Municipal", value: "Owerri-Municipal" },
      { label: "Owerri-North", value: "Owerri-North" },
      { label: "Owerri-West", value: "Owerri-West" },
    ],
  },
  {
    value: "Jigawa",
    label: "Jigawa",
    lgas: [
      { label: "Auyo", value: "Auyo" },
      { label: "Babura", value: "Babura" },
      { label: "Biriniwa", value: "Biriniwa" },
      { label: "Birnin-Kudu", value: "Birnin-Kudu" },
      { label: "Buji", value: "Buji" },
      { label: "Dutse", value: "Dutse" },
      { label: "Gagarawa", value: "Gagarawa" },
      { label: "Garki", value: "Garki" },
      { label: "Gumel", value: "Gumel" },
      { label: "Guri", value: "Guri" },
      { label: "Gwaram", value: "Gwaram" },
      { label: "Gwiwa", value: "Gwiwa" },
      { label: "Hadejia", value: "Hadejia" },
      { label: "Jahun", value: "Jahun" },
      { label: "Kafin-Hausa", value: "Kafin-Hausa" },
      { label: "Kaugama", value: "Kaugama" },
      { label: "Kazaure", value: "Kazaure" },
      { label: "Kiri kasama", value: "Kiri kasama" },
      { label: "Maigatari", value: "Maigatari" },
      { label: "Malam Madori", value: "Malam Madori" },
      { label: "Miga", value: "Miga" },
      { label: "Ringim", value: "Ringim" },
      { label: "Roni", value: "Roni" },
      { label: "Sule-Tankarkar", value: "Sule-Tankarkar" },
      { label: "Taura", value: "Taura" },
      { label: "Yankwashi", value: "Yankwashi" },
    ],
  },
  {
    value: "Kebbi",
    label: "Kebbi",
    lgas: [
      { label: "Aleiro", value: "Aleiro" },
      { label: "Arewa-Dandi", value: "Arewa-Dandi" },
      { label: "Argungu", value: "Argungu" },
      { label: "Augie", value: "Augie" },
      { label: "Bagudo", value: "Bagudo" },
      { label: "Birnin-Kebbi", value: "Birnin-Kebbi" },
      { label: "Bunza", value: "Bunza" },
      { label: "Dandi", value: "Dandi" },
      { label: "Fakai", value: "Fakai" },
      { label: "Gwandu", value: "Gwandu" },
      { label: "Jega", value: "Jega" },
      { label: "Kalgo", value: "Kalgo" },
      { label: "Koko-Besse", value: "Koko-Besse" },
      { label: "Maiyama", value: "Maiyama" },
      { label: "Ngaski", value: "Ngaski" },
      { label: "Sakaba", value: "Sakaba" },
      { label: "Shanga", value: "Shanga" },
      { label: "Suru", value: "Suru" },
      { label: "Wasagu/Danko", value: "Wasagu/Danko" },
      { label: "Yauri", value: "Yauri" },
      { label: "Zuru", value: "Zuru" },
    ],
  },
  {
    value: "Kaduna",
    label: "Kaduna",
    lgas: [
      { label: "Birnin-Gwari", value: "Birnin-Gwari" },
      { label: "Chikun", value: "Chikun" },
      { label: "Giwa", value: "Giwa" },
      { label: "Igabi", value: "Igabi" },
      { label: "Ikara", value: "Ikara" },
      { label: "Jaba", value: "Jaba" },
      { label: "Jema'A", value: "Jema'A" },
      { label: "Kachia", value: "Kachia" },
      { label: "Kaduna-North", value: "Kaduna-North" },
      { label: "Kaduna-South", value: "Kaduna-South" },
      { label: "Kagarko", value: "Kagarko" },
      { label: "Kajuru", value: "Kajuru" },
      { label: "Kaura", value: "Kaura" },
      { label: "Kauru", value: "Kauru" },
      { label: "Kubau", value: "Kubau" },
      { label: "Kudan", value: "Kudan" },
      { label: "Lere", value: "Lere" },
      { label: "Makarfi", value: "Makarfi" },
      { label: "Sabon-Gari", value: "Sabon-Gari" },
      { label: "Sanga", value: "Sanga" },
      { label: "Soba", value: "Soba" },
      { label: "Zangon-Kataf", value: "Zangon-Kataf" },
      { label: "Zaria", value: "Zaria" },
    ],
  },
  {
    value: "Kano",
    label: "Kano",
    lgas: [
      { label: "Ajingi", value: "Ajingi" },
      { label: "Albasu", value: "Albasu" },
      { label: "Bagwai", value: "Bagwai" },
      { label: "Bebeji", value: "Bebeji" },
      { label: "Bichi", value: "Bichi" },
      { label: "Bunkure", value: "Bunkure" },
      { label: "Dala", value: "Dala" },
      { label: "Dambatta", value: "Dambatta" },
      { label: "Dawakin-Kudu", value: "Dawakin-Kudu" },
      { label: "Dawakin-Tofa", value: "Dawakin-Tofa" },
      { label: "Doguwa", value: "Doguwa" },
      { label: "Fagge", value: "Fagge" },
      { label: "Gabasawa", value: "Gabasawa" },
      { label: "Garko", value: "Garko" },
      { label: "Garun-Mallam", value: "Garun-Mallam" },
      { label: "Gaya", value: "Gaya" },
      { label: "Gezawa", value: "Gezawa" },
      { label: "Gwale", value: "Gwale" },
      { label: "Gwarzo", value: "Gwarzo" },
      { label: "Kabo", value: "Kabo" },
      { label: "Kano-Municipal", value: "Kano-Municipal" },
      { label: "Karaye", value: "Karaye" },
      { label: "Kibiya", value: "Kibiya" },
      { label: "Kiru", value: "Kiru" },
      { label: "Kumbotso", value: "Kumbotso" },
      { label: "Kunchi", value: "Kunchi" },
      { label: "Kura", value: "Kura" },
      { label: "Madobi", value: "Madobi" },
      { label: "Makoda", value: "Makoda" },
      { label: "Minjibir", value: "Minjibir" },
      { label: "Nasarawa", value: "Nasarawa" },
      { label: "Rano", value: "Rano" },
      { label: "Rimin-Gado", value: "Rimin-Gado" },
      { label: "Rogo", value: "Rogo" },
      { label: "Shanono", value: "Shanono" },
      { label: "Sumaila", value: "Sumaila" },
      { label: "Takai", value: "Takai" },
      { label: "Tarauni", value: "Tarauni" },
      { label: "Tofa", value: "Tofa" },
      { label: "Tsanyawa", value: "Tsanyawa" },
      { label: "Tudun-Wada", value: "Tudun-Wada" },
      { label: "Ungogo", value: "Ungogo" },
      { label: "Warawa", value: "Warawa" },
      { label: "Wudil", value: "Wudil" },
    ],
  },
  {
    value: "Kogi",
    label: "Kogi",
    lgas: [
      { label: "Adavi", value: "Adavi" },
      { label: "Ajaokuta", value: "Ajaokuta" },
      { label: "Ankpa", value: "Ankpa" },
      { label: "Dekina", value: "Dekina" },
      { label: "Ibaji", value: "Ibaji" },
      { label: "Idah", value: "Idah" },
      { label: "Igalamela-Odolu", value: "Igalamela-Odolu" },
      { label: "Ijumu", value: "Ijumu" },
      { label: "Kabba/Bunu", value: "Kabba/Bunu" },
      { label: "Kogi", value: "Kogi" },
      { label: "Lokoja", value: "Lokoja" },
      { label: "Mopa-Muro", value: "Mopa-Muro" },
      { label: "Ofu", value: "Ofu" },
      { label: "Ogori/Magongo", value: "Ogori/Magongo" },
      { label: "Okehi", value: "Okehi" },
      { label: "Okene", value: "Okene" },
      { label: "Olamaboro", value: "Olamaboro" },
      { label: "Omala", value: "Omala" },
      { label: "Oyi", value: "Oyi" },
      { label: "Yagba-East", value: "Yagba-East" },
      { label: "Yagba-West", value: "Yagba-West" },
    ],
  },
  {
    value: "Katsina",
    label: "Katsina",
    lgas: [
      { label: "Bakori", value: "Bakori" },
      { label: "Batagarawa", value: "Batagarawa" },
      { label: "Batsari", value: "Batsari" },
      { label: "Baure", value: "Baure" },
      { label: "Bindawa", value: "Bindawa" },
      { label: "Charanchi", value: "Charanchi" },
      { label: "Dan-Musa", value: "Dan-Musa" },
      { label: "Dandume", value: "Dandume" },
      { label: "Danja", value: "Danja" },
      { label: "Daura", value: "Daura" },
      { label: "Dutsi", value: "Dutsi" },
      { label: "Dutsin-Ma", value: "Dutsin-Ma" },
      { label: "Faskari", value: "Faskari" },
      { label: "Funtua", value: "Funtua" },
      { label: "Ingawa", value: "Ingawa" },
      { label: "Jibia", value: "Jibia" },
      { label: "Kafur", value: "Kafur" },
      { label: "Kaita", value: "Kaita" },
      { label: "Kankara", value: "Kankara" },
      { label: "Kankia", value: "Kankia" },
      { label: "Katsina", value: "Katsina" },
      { label: "Kurfi", value: "Kurfi" },
      { label: "Kusada", value: "Kusada" },
      { label: "Mai-Adua", value: "Mai-Adua" },
      { label: "Malumfashi", value: "Malumfashi" },
      { label: "Mani", value: "Mani" },
      { label: "Mashi", value: "Mashi" },
      { label: "Matazu", value: "Matazu" },
      { label: "Musawa", value: "Musawa" },
      { label: "Rimi", value: "Rimi" },
      { label: "Sabuwa", value: "Sabuwa" },
      { label: "Safana", value: "Safana" },
      { label: "Sandamu", value: "Sandamu" },
      { label: "Zango", value: "Zango" },
    ],
  },
  {
    value: "Kwara",
    label: "Kwara",
    lgas: [
      { label: "Asa", value: "Asa" },
      { label: "Baruten", value: "Baruten" },
      { label: "Edu", value: "Edu" },
      { label: "Ekiti (Araromi/Opin)", value: "Ekiti (Araromi/Opin)" },
      { label: "Ilorin-East", value: "Ilorin-East" },
      { label: "Ilorin-South", value: "Ilorin-South" },
      { label: "Ilorin-West", value: "Ilorin-West" },
      { label: "Isin", value: "Isin" },
      { label: "Kaiama", value: "Kaiama" },
      { label: "Moro", value: "Moro" },
      { label: "Offa", value: "Offa" },
      { label: "Oke-Ero", value: "Oke-Ero" },
      { label: "Oyun", value: "Oyun" },
      { label: "Pategi", value: "Pategi" },
    ],
  },
  {
    value: "Lagos",
    label: "Lagos",
    lgas: [
      { label: "Agege", value: "Agege" },
      { label: "Ajeromi-Ifelodun", value: "Ajeromi-Ifelodun" },
      { label: "Alimosho", value: "Alimosho" },
      { label: "Amuwo-Odofin", value: "Amuwo-Odofin" },
      { label: "Apapa", value: "Apapa" },
      { label: "Badagry", value: "Badagry" },
      { label: "Epe", value: "Epe" },
      { label: "Eti-Osa", value: "Eti-Osa" },
      { label: "Ibeju-Lekki", value: "Ibeju-Lekki" },
      { label: "Ifako-Ijaiye", value: "Ifako-Ijaiye" },
      { label: "Ikeja", value: "Ikeja" },
      { label: "Ikorodu", value: "Ikorodu" },
      { label: "Kosofe", value: "Kosofe" },
      { label: "Lagos-Island", value: "Lagos-Island" },
      { label: "Lagos-Mainland", value: "Lagos-Mainland" },
      { label: "Mushin", value: "Mushin" },
      { label: "Ojo", value: "Ojo" },
      { label: "Oshodi-Isolo", value: "Oshodi-Isolo" },
      { label: "Shomolu", value: "Shomolu" },
      { label: "Surulere", value: "Surulere" },
      { label: "Yewa-South", value: "Yewa-South" },
    ],
  },
  {
    value: "Nasarawa",
    label: "Nasarawa",
    lgas: [
      { label: "Akwanga", value: "Akwanga" },
      { label: "Awe", value: "Awe" },
      { label: "Doma", value: "Doma" },
      { label: "Karu", value: "Karu" },
      { label: "Keana", value: "Keana" },
      { label: "Keffi", value: "Keffi" },
      { label: "Kokona", value: "Kokona" },
      { label: "Lafia", value: "Lafia" },
      { label: "Nasarawa", value: "Nasarawa" },
      { label: "Nasarawa-Eggon", value: "Nasarawa-Eggon" },
      { label: "Obi", value: "Obi" },
      { label: "Wamba", value: "Wamba" },
      { label: "Toto", value: "Toto" },
    ],
  },
  {
    value: "Niger",
    label: "Niger",
    lgas: [
      { label: "Agaie", value: "Agaie" },
      { label: "Agwara", value: "Agwara" },
      { label: "Bida", value: "Bida" },
      { label: "Borgu", value: "Borgu" },
      { label: "Bosso", value: "Bosso" },
      { label: "Chanchaga", value: "Chanchaga" },
      { label: "Edati", value: "Edati" },
      { label: "Gbako", value: "Gbako" },
      { label: "Gurara", value: "Gurara" },
      { label: "Katcha", value: "Katcha" },
      { label: "Kontagora", value: "Kontagora" },
      { label: "Lapai", value: "Lapai" },
      { label: "Lavun", value: "Lavun" },
      { label: "Magama", value: "Magama" },
      { label: "Mariga", value: "Mariga" },
      { label: "Mashegu", value: "Mashegu" },
      { label: "Mokwa", value: "Mokwa" },
      { label: "Moya", value: "Moya" },
      { label: "Paikoro", value: "Paikoro" },
      { label: "Rafi", value: "Rafi" },
      { label: "Rijau", value: "Rijau" },
      { label: "Shiroro", value: "Shiroro" },
      { label: "Suleja", value: "Suleja" },
      { label: "Tafa", value: "Tafa" },
      { label: "Wushishi", value: "Wushishi" },
    ],
  },
  {
    value: "Ogun",
    label: "Ogun",
    lgas: [
      { label: "Abeokuta-North", value: "Abeokuta-North" },
      { label: "Abeokuta-South", value: "Abeokuta-South" },
      { label: "Ado-Odo/Ota", value: "Ado-Odo/Ota" },
      { label: "Ewekoro", value: "Ewekoro" },
      { label: "Ifo", value: "Ifo" },
      { label: "Ijebu-East", value: "Ijebu-East" },
      { label: "Ijebu-North", value: "Ijebu-North" },
      { label: "Ijebu-North-East", value: "Ijebu-North-East" },
      { label: "Ijebu-Ode", value: "Ijebu-Ode" },
      { label: "Ikenne", value: "Ikenne" },
      { label: "Imeko-Afon", value: "Imeko-Afon" },
      { label: "Ipokia", value: "Ipokia" },
      { label: "Obafemi-Owode", value: "Obafemi-Owode" },
      { label: "Odeda", value: "Odeda" },
      { label: "Odogbolu", value: "Odogbolu" },
      { label: "Ogun-Waterside", value: "Ogun-Waterside" },
      { label: "Remo-North", value: "Remo-North" },
      { label: "Shagamu", value: "Shagamu" },
      { label: "Yewa North", value: "Yewa North" },
    ],
  },
  {
    value: "Ondo",
    label: "Ondo",
    lgas: [
      { label: "Akoko North-East", value: "Akoko North-East" },
      { label: "Akoko North-West", value: "Akoko North-West" },
      { label: "Akoko South-West", value: "Akoko South-West" },
      { label: "Akoko South-East", value: "Akoko South-East" },
      { label: "Akure-North", value: "Akure-North" },
      { label: "Akure-South", value: "Akure-South" },
      { label: "Ese-Odo", value: "Ese-Odo" },
      { label: "Idanre", value: "Idanre" },
      { label: "Ifedore", value: "Ifedore" },
      { label: "Ilaje", value: "Ilaje" },
      { label: "Ile-Oluji-Okeigbo", value: "Ile-Oluji-Okeigbo" },
      { label: "Irele", value: "Irele" },
      { label: "Odigbo", value: "Odigbo" },
      { label: "Okitipupa", value: "Okitipupa" },
      { label: "Ondo West", value: "Ondo West" },
      { label: "Ondo-East", value: "Ondo-East" },
      { label: "Ose", value: "Ose" },
      { label: "Owo", value: "Owo" },
    ],
  },
  {
    value: "Osun",
    label: "Osun",
    lgas: [
      { label: "Atakumosa West", value: "Atakumosa West" },
      { label: "Atakumosa East", value: "Atakumosa East" },
      { label: "Ayedaade", value: "Ayedaade" },
      { label: "Ayedire", value: "Ayedire" },
      { label: "Boluwaduro", value: "Boluwaduro" },
      { label: "Boripe", value: "Boripe" },
      { label: "Ede South", value: "Ede South" },
      { label: "Ede North", value: "Ede North" },
      { label: "Egbedore", value: "Egbedore" },
      { label: "Ejigbo", value: "Ejigbo" },
      { label: "Ife North", value: "Ife North" },
      { label: "Ife South", value: "Ife South" },
      { label: "Ife-Central", value: "Ife-Central" },
      { label: "Ife-East", value: "Ife-East" },
      { label: "Ifelodun", value: "Ifelodun" },
      { label: "Ila", value: "Ila" },
      { label: "Ilesa-East", value: "Ilesa-East" },
      { label: "Ilesa-West", value: "Ilesa-West" },
      { label: "Irepodun", value: "Irepodun" },
      { label: "Irewole", value: "Irewole" },
      { label: "Isokan", value: "Isokan" },
      { label: "Iwo", value: "Iwo" },
      { label: "Obokun", value: "Obokun" },
      { label: "Odo-Otin", value: "Odo-Otin" },
      { label: "Ola Oluwa", value: "Ola Oluwa" },
      { label: "Olorunda", value: "Olorunda" },
      { label: "Oriade", value: "Oriade" },
      { label: "Orolu", value: "Orolu" },
      { label: "Osogbo", value: "Osogbo" },
    ],
  },
  {
    value: "Oyo",
    label: "Oyo",
    lgas: [
      { label: "Afijio", value: "Afijio" },
      { label: "Akinyele", value: "Akinyele" },
      { label: "Atiba", value: "Atiba" },
      { label: "Atisbo", value: "Atisbo" },
      { label: "Egbeda", value: "Egbeda" },
      { label: "Ibadan North", value: "Ibadan North" },
      { label: "Ibadan North-East", value: "Ibadan North-East" },
      { label: "Ibadan North-West", value: "Ibadan North-West" },
      { label: "Ibadan South-East", value: "Ibadan South-East" },
      { label: "Ibadan South-West", value: "Ibadan South-West" },
      { label: "Ibarapa-Central", value: "Ibarapa-Central" },
      { label: "Ibarapa-East", value: "Ibarapa-East" },
      { label: "Ibarapa-North", value: "Ibarapa-North" },
      { label: "Ido", value: "Ido" },
      { label: "Ifedayo", value: "Ifedayo" },
      { label: "Irepo", value: "Irepo" },
      { label: "Iseyin", value: "Iseyin" },
      { label: "Itesiwaju", value: "Itesiwaju" },
      { label: "Iwajowa", value: "Iwajowa" },
      { label: "Kajola", value: "Kajola" },
      { label: "Lagelu", value: "Lagelu" },
      { label: "Ogo-Oluwa", value: "Ogo-Oluwa" },
      { label: "Ogbomosho-North", value: "Ogbomosho-North" },
      { label: "Ogbomosho-South", value: "Ogbomosho-South" },
      { label: "Olorunsogo", value: "Olorunsogo" },
      { label: "Oluyole", value: "Oluyole" },
      { label: "Ona-Ara", value: "Ona-Ara" },
      { label: "Orelope", value: "Orelope" },
      { label: "Ori-Ire", value: "Ori-Ire" },
      { label: "Oyo-West", value: "Oyo-West" },
      { label: "Oyo-East", value: "Oyo-East" },
      { label: "Saki-East", value: "Saki-East" },
      { label: "Saki-West", value: "Saki-West" },
      { label: "Surulere", value: "Surulere" },
    ],
  },
  {
    value: "Plateau",
    label: "Plateau",
    lgas: [
      { label: "Barkin-Ladi", value: "Barkin-Ladi" },
      { label: "Bassa", value: "Bassa" },
      { label: "Bokkos", value: "Bokkos" },
      { label: "Jos-East", value: "Jos-East" },
      { label: "Jos-North", value: "Jos-North" },
      { label: "Jos-South", value: "Jos-South" },
      { label: "Kanam", value: "Kanam" },
      { label: "Kanke", value: "Kanke" },
      { label: "Langtang-North", value: "Langtang-North" },
      { label: "Langtang-South", value: "Langtang-South" },
      { label: "Mangu", value: "Mangu" },
      { label: "Mikang", value: "Mikang" },
      { label: "Pankshin", value: "Pankshin" },
      { label: "Qua'an Pan", value: "Qua'an Pan" },
      { label: "Riyom", value: "Riyom" },
      { label: "Shendam", value: "Shendam" },
      { label: "Wase", value: "Wase" },
    ],
  },
  {
    value: "Rivers",
    label: "Rivers",
    lgas: [
      { label: "Abua/Odual", value: "Abua/Odual" },
      { label: "Ahoada-East", value: "Ahoada-East" },
      { label: "Ahoada-West", value: "Ahoada-West" },
      { label: "Akuku Toru", value: "Akuku Toru" },
      { label: "Andoni", value: "Andoni" },
      { label: "Asari-Toru", value: "Asari-Toru" },
      { label: "Bonny", value: "Bonny" },
      { label: "Degema", value: "Degema" },
      { label: "Eleme", value: "Eleme" },
      { label: "Emuoha", value: "Emuoha" },
      { label: "Etche", value: "Etche" },
      { label: "Gokana", value: "Gokana" },
      { label: "Ikwerre", value: "Ikwerre" },
      { label: "Khana", value: "Khana" },
      { label: "Obio/Akpor", value: "Obio/Akpor" },
      { label: "Ogba-Egbema-Ndoni", value: "Ogba-Egbema-Ndoni" },
      { label: "Ogba/Egbema/Ndoni", value: "Ogba/Egbema/Ndoni" },
      { label: "Ogu/Bolo", value: "Ogu/Bolo" },
      { label: "Okrika", value: "Okrika" },
      { label: "Omuma", value: "Omuma" },
      { label: "Opobo/Nkoro", value: "Opobo/Nkoro" },
      { label: "Oyigbo", value: "Oyigbo" },
      { label: "Port-Harcourt", value: "Port-Harcourt" },
      { label: "Tai", value: "Tai" },
    ],
  },
  {
    value: "Sokoto",
    label: "Sokoto",
    lgas: [
      { label: "Binji", value: "Binji" },
      { label: "Bodinga", value: "Bodinga" },
      { label: "Dange-Shuni", value: "Dange-Shuni" },
      { label: "Gada", value: "Gada" },
      { label: "Goronyo", value: "Goronyo" },
      { label: "Gudu", value: "Gudu" },
      { label: "Gwadabawa", value: "Gwadabawa" },
      { label: "Illela", value: "Illela" },
      { label: "Kebbe", value: "Kebbe" },
      { label: "Kware", value: "Kware" },
      { label: "Rabah", value: "Rabah" },
      { label: "Sabon Birni", value: "Sabon Birni" },
      { label: "Shagari", value: "Shagari" },
      { label: "Silame", value: "Silame" },
      { label: "Sokoto-North", value: "Sokoto-North" },
      { label: "Sokoto-South", value: "Sokoto-South" },
      { label: "Tambuwal", value: "Tambuwal" },
      { label: "Tangaza", value: "Tangaza" },
      { label: "Tureta", value: "Tureta" },
      { label: "Wamako", value: "Wamako" },
      { label: "Wurno", value: "Wurno" },
      { label: "Yabo", value: "Yabo" },
    ],
  },
  {
    value: "Taraba",
    label: "Taraba",
    lgas: [
      { label: "Ardo-Kola", value: "Ardo-Kola" },
      { label: "Bali", value: "Bali" },
      { label: "Donga", value: "Donga" },
      { label: "Gashaka", value: "Gashaka" },
      { label: "Gassol", value: "Gassol" },
      { label: "Ibi", value: "Ibi" },
      { label: "Jalingo", value: "Jalingo" },
      { label: "Karim-Lamido", value: "Karim-Lamido" },
      { label: "Kurmi", value: "Kurmi" },
      { label: "Lau", value: "Lau" },
      { label: "Sardauna", value: "Sardauna" },
      { label: "Takum", value: "Takum" },
      { label: "Ussa", value: "Ussa" },
      { label: "Wukari", value: "Wukari" },
      { label: "Yorro", value: "Yorro" },
      { label: "Zing", value: "Zing" },
    ],
  },
  {
    value: "Yobe",
    label: "Yobe",
    lgas: [
      { label: "Bade", value: "Bade" },
      { label: "Bursari", value: "Bursari" },
      { label: "Damaturu", value: "Damaturu" },
      { label: "Fika", value: "Fika" },
      { label: "Fune", value: "Fune" },
      { label: "Geidam", value: "Geidam" },
      { label: "Gujba", value: "Gujba" },
      { label: "Gulani", value: "Gulani" },
      { label: "Jakusko", value: "Jakusko" },
      { label: "Karasuwa", value: "Karasuwa" },
      { label: "Machina", value: "Machina" },
      { label: "Nangere", value: "Nangere" },
      { label: "Nguru", value: "Nguru" },
      { label: "Potiskum", value: "Potiskum" },
      { label: "Tarmuwa", value: "Tarmuwa" },
      { label: "Yunusari", value: "Yunusari" },
      { label: "Yusufari", value: "Yusufari" },
    ],
  },
  {
    value: "Zamfara",
    label: "Zamfara",
    lgas: [
      { label: "Anka", value: "Anka" },
      { label: "Bakura", value: "Bakura" },
      { label: "Birnin Magaji/Kiyaw", value: "Birnin Magaji/Kiyaw" },
      { label: "Bukkuyum", value: "Bukkuyum" },
      { label: "Bungudu", value: "Bungudu" },
      { label: "Gummi", value: "Gummi" },
      { label: "Gusau", value: "Gusau" },
      { label: "Isa", value: "Isa" },
      { label: "Kaura-Namoda", value: "Kaura-Namoda" },
      { label: "Kiyawa", value: "Kiyawa" },
      { label: "Maradun", value: "Maradun" },
      { label: "Maru", value: "Maru" },
      { label: "Shinkafi", value: "Shinkafi" },
      { label: "Talata-Mafara", value: "Talata-Mafara" },
      { label: "Tsafe", value: "Tsafe" },
      { label: "Zurmi", value: "Zurmi" },
    ],
  },
];

export default statesData;
